### ISSUE TITLE
Polyglot always sets html ft as jinja

### ISSUE THREAD

**Issue by joaoponceleao** [sheerun/vim-polyglot#108]
Hi,
I keep getting django or angularness html files set as ft=jinja by polyglot.
Disabling the polyglot plugin through the plugin manager (plug) takes care of the issue.
Disabling the jinja language by setting `let g:polyglot_disabled='jinja'`, only disables the syntax highlighting for the html file. The ft still gets set as 'jinja'.
Looking at the source code it seems that `fun! s:SelectHTML()` gets called no matter what (which would imply issues with other html types), but I can't see why that would be.

**Comment by patrickng** [comment]
This also happens with HTML files with handlebars/mustache syntax when jinja is left enabled. This is because [line 198](https://github.com/sheerun/vim-polyglot/blob/b0823d20685d0c03e70de3abfc85d79a8188d292/ftdetect/polyglot.vim#L198) checks for `{{.*}}` in the regex.. 

The correct syntax to disable seems to be `let g:polyglot_disabled = ['jinja']` 
Make sure it's in an array and not a string. 

If you're like me and you're using something like [The Ultimate Vimrc](https://github.com/amix/vimrc), you can't put that in my_configs.vim since the plugin gets loaded first which does the check against the array before the array is even defined. You'll have to add another file to source in ~/.vimrc or define the array to disable before plugins_config.vim.

I've never used plug but it seems like maybe plug is also loading the plugin first. Try putting `let g:polyglot_disabled = ['jinja']` before the plug section in your ~/.vimrc

**Comment by joaoponceleao** [comment]
Thanks @patrickng.

I can confirm that putting the `let g:polyglot_disabled = ['jinja']` before the plug section solves the issue. Will reference this issue in the vim-plug repo for other users.

**Comment by joaoponceleao** [comment]
Reopening issue as vim-plug developer suggests that the problem lies in polyglot.
The `polyglot_disable line` just needs to come before the `filetype` line, regardless of whether vim-plug is used. See his note on the referenced thread.

**Comment by sheerun** [comment]
I've removed jinja syntax from vim-plyglot until I find fixed package

**Comment by sheerun** [comment]
@joaoponceleao As for issue you're mentioning, I'm not sure how to fix it from my side.

**Comment by smarinov** [comment]
I think this might have been solved after you removed jinja support, see https://github.com/Glench/Vim-Jinja2-Syntax/pull/13. I am currently running both plugins and files are correctly recognised if they are pure HTML or jinja.
