### ISSUE TITLE
Highlight code blocks in Markdown files

### ISSUE THREAD

**Issue by IonicaBizau** [sheerun/vim-polyglot#152]
It would be really nice if the code blocks code would be highlighted in Markdown files.

This is one of my favorite VIM plugins! Amazing work! :sparkles:

**Comment by whitelynx** [comment]
Since this repo just aggregates code from other repos for each language, you probably want to look at [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown) instead.

The `README.md` there shows that it has [a `g:vim_markdown_fenced_languages` option](https://github.com/plasticboy/vim-markdown#fenced-code-block-languages) (similar to the `g:markdown_fenced_languages` option in [Vim's builtin `markdown.vim`](https://github.com/tpope/vim-markdown)) that provides this functionality.

**Comment by sheerun** [comment]
Lik @whitelynx says. If you can find better markdown package, please send PR that updates repository name in `build` file. You can also send PR with better default options to `config.vim`.

**Comment by scwood** [comment]
When I install plasticboy/vim-markdown as a standalone package fenced code blocks work, however when I use vim-polyglot they aren't working. Any ideas?

**Comment by hmohamad** [comment]
Same here, no fenced code block highlighting with vim-polyglot

**Comment by IonicaBizau** [comment]
Yes, same here...

**Comment by peter50216** [comment]
Seems that the feature is implemented in ftplugin, and vim-polyglot only get the syntax folder.

**Comment by luke-jj** [comment]
This issue can be fixed by configuring [vim-polyglot](https://github.com/sheerun/vim-polyglot/) in your `~/.vimrc` and loading the [vim-markdown](https://github.com/plasticboy/vim-markdown) package separately on its own.

```
" This line prevents polyglot from loading markdown packages.
let g:polyglot_disabled = ['md', 'markdown']

" This line configures markdown-vim to highlight code blocks for given languages.
let g:markdown_fenced_languages = ['html', 'css', 'scss', 'sql', 'javascript', 'go', 'python', 'bash=sh', 'c', 'ruby']
```

**Comment by sheerun** [comment]
vim-polyglot now includes ftplugin part so it should work
