### ISSUE TITLE
Rewrite build script to vimscript

### ISSUE THREAD

**Issue by sheerun** [sheerun/vim-polyglot#192]
I encourage anyone to take this one, as I'm short on time, and don't have much vimscript expertise.

Rewriting the [build](https://github.com/sheerun/vim-polyglot/blob/master/build) script to vimscript would allow awesome features like `:PolyglotUpdate` and being cross-platform. Currenty bash and few unix tools are required. 

I think one could borrow some code from tools like vim-plug

**Comment by vaz** [comment]
Commenting out of potential interest so I can see myself as "participating". I'll let you know if I get to working on something. (Also thanks for this package, it's brilliant considering the package management situation in Vim is... what it is.)

What's the min Vim version to support? I assume it's 7.x (more specific might be important, not sure). So no Vim 8 async support (though then you probably end up needing to write separate support for NeoVim's plugin platform instead of the old workarounds that work on all of them... so your thought about looking at something like vim-plug is a good one, since it does a good job handling and displaying an update process without locking up on Vim 7.x+ and works just as well on NeoVim.

**Comment by sheerun** [comment]
Hey, thank you :)

I think 7.x is more than enough. Generally update process can be blocking, as it's quite fast (~30 seconds) and rarely used. I think you could borrow some codebase from vim-plug as it does similar thing (downloading packages from GitHub). I'd ask that the packages shoudn't be git cloned but rather downloaded as .zip or .tar.gz packages and unpacked (it's way faster, and that's how it's currently done in build.sh). I've added you to collaborators to maybe make things easier :)

**Comment by sheerun** [comment]
Also, it's unfortunately obligatory that .tar.gz or .zip packages are downloaded in parallel, as it takes way to much time to download them sequentially.

**Comment by sheerun** [comment]
There can be simpler version of this task: `:PolyglotUpdate` that just runs build script inside vim-polyglot directory

**Comment by h-michael** [comment]
I'm interested in this topic.

**Comment by sheerun** [comment]
@h-michael Feel free to send a PR

**Comment by sheerun** [comment]
this task is still up for grabs

**Comment by qstrahl** [comment]
@sheerun I'll take a look at it if you take a look at #429 c:
