### ISSUE TITLE
Use vimtex instead of LaTeX-Box

### ISSUE THREAD

**Issue by vbrandl** [sheerun/vim-polyglot#204]
Have you considered using [vimtex](https://github.com/lervag/vimtex) instead if LaTeX-Box as a LaTeX plugin? The latest commit for LaTeX-Box was on 1 Jun 2015. For vimtex it was yesterday. Also vimtex is based on LaTeX-Box but introduces a few new features.
I think it would be cool to see vimtex as LaTeX plugin in polyglot

**Comment by sheerun** [comment]
Unfortunately I get some errors when trying to include it. Also it seems to do more than just highlighting - vim-polyglot is plugin pack just for syntax / indentation, no advanced features.

**Comment by dojoteef** [comment]
I'm posting this here in case anyone runs into the same issue, because it certainly surprised me!

If you use both [vimtex] and vim-polyglot you must add the following to your vimrc if you want to be able to use [vimtex] ([see for more info](https://github.com/lervag/vimtex/issues/450#issuecomment-216110767)):
```vim
let g:polyglot_disabled = ['latex']
```

@sheerun Considering you said
```
vim-polyglot is plugin pack just for syntax / indentation, no advanced features
```

I would urge you to remove [LaTeX-Box] from vim-polyglot, as it DOES more than just syntax/indentation. Basically it installs a number of key mappings. Those mappings happen to interfere with [vimtex]. It took some time to debug the issue, since I assumed [vimtex] was the culprit, when in fact it turns out vim-polyglot was. That definitely took me by surprise as I thought vim-polyglot was only for syntax/indentation (as you stated above).

[vimtex]: https://github.com/lervag/vimtex
[LaTeX-Box]: https://github.com/LaTeX-Box-Team/LaTeX-Box

**Comment by dojoteef** [comment]
Having just looked at [ftplugin/latex-box/mappings.vim#5-7](https://github.com/sheerun/vim-polyglot/blob/master/ftplugin/latex-box/mappings.vim#L5-L7), I see you have:

```vim
if exists("g:LatexBox_no_mappings")
	finish
endif
```

I guess the other option is to disable [LaTeX-Box] mappings by default. That way it does not have unintended consequences, yet people can opt-in if they want.

[LaTeX-Box]: https://github.com/LaTeX-Box-Team/LaTeX-Box

**Comment by albertnetymk** [comment]
Bitten by the mappings introduced by LatexBox; could be beneficial to mention this conflict (with vimtex) in readme.

**Comment by delijati** [comment]
+1

**Comment by cideM** [comment]
And here I was starting to doubt my sanity when **toggling the table of contents didn't take `vimtex_toc_config` into account, but opening it did.** Turns out that LaTeX-Box mappings were active and `<localleader>lt` was handled by LaTeX-Box rather than vimtex
