### ISSUE TITLE
Disabling c/c++ highlighting is "weird"

### ISSUE THREAD

**Issue by humodz** [sheerun/vim-polyglot#306]
To disable C or C++, it's necessary to write:
```
let g:polyglot_disabled = ['c/c++', 'c++11']
```
Adding `c++11` is necessary **even for plain C**, otherwise function names and functions from the standard lib get highlighted differently. My first instinct was that polyglot_disabled would take the actual filetypes, as in `['c', 'cpp']`, instead of that. Is there a reason behind this?

The c++11 check is done by `vim-polyglot/after/syntax/c.vim` and  `vim-polyglot/after/syntax/cpp.vim`.
The c/c++ check is done by `vim-polyglot/syntax/c.vim` and `vim-polyglot/syntax/cpp.vim`

**Comment by CH-DanReif** [comment]
The reason is these two lines: https://github.com/sheerun/vim-polyglot/blob/a26134de3c09f9725667e14e7073a701bcff4e19/build#L152-L153 .  `c++11`, as you noted, only adds those two files in `after`.  So my first thought is that disabling `c++11` should disable only `c++11`, but disabling `c/c++` should also disable `c++11`.  But then I think about it a bit more; surely someone, somewhere might want to bring in their own replacement for `c/c++`, while continuing to use our `c++11`.

If we had a good way to raise a one-time warning to the user, _lint_-style, this would be a perfect fit to raise there.  But outside of that, I'm not sure what fix I'd be comfortable with.  What would you suggest?
