### ISSUE TITLE
Broken Go autoloading (can't disable polyglot version since `bde56bc` )

### ISSUE THREAD

**Issue by jcorbin** [sheerun/vim-polyglot#309]
Now fails with:
```
Error detected while processing /Users/joshua/.config/nvim/plugged/vim-go/plugin/go.vim:
line   16:
E117: Unknown function: go#config#VersionWarning
E15: Invalid expression: go#config#VersionWarning() != 0 && (v:version < 704 || (v:version == 704 && !has('patch1689'))) && !has('nvim')
Press ENTER or type command to continue
```

Reverting to v3.3.2 (or any version before `bde56bc`) fixes; as you can see, I try to have both: https://github.com/jcorbin/home/blob/master/.vimrc#L49 .

**Comment by CH-DanReif** [comment]
This is because autoload is giving up and going home.  It's looking for `go/config` and finding it at https://github.com/sheerun/vim-polyglot/blob/master/autoload/go/config.vim .  But that file doesn't define anything (because you've disabled polyglot's go support).  It then doesn't attempt to find that same file anywhere else.

Perhaps https://github.com/junegunn/vim-plug supports the concept of setting a special value in our autoload file that would indicate that it's _disabled_, but still _present_.  Perhaps vim-plug would honor ordering in its searching of autoload directories, if you put `fatih/vim-go` first.  Perhaps manually loading the autoload file from `fatih/vim-go` would preclude vim from subsequently searching the autoload path.  I'm not sure about any of these, but I don't see how it would be possible for us to solve this in this project.

**Comment by akmassey** [comment]
For what it's worth in case anyone else ends up here from searching for a solution to this, I believe this is order dependent.  If you load polyglot after your language plugins (for those plugins you're doing manually and disabling in polyglot), then you won't run into this problem.
