### ISSUE TITLE
Add support for CSS template literals in JavaScript (à la styled-components, emotion, glamor)

### ISSUE THREAD

**Issue by chaucerbao** [sheerun/vim-polyglot#323]
It would be great to have support for CSS template literals within JavaScript files.

https://github.com/styled-components/vim-styled-components

> Vim bundle for styled-components, diet-cola, emotion and experimental glamor/styled content in javascript files.

**Comment by joeytwiddle** [comment]
This "language extension" doesn't have a specific file extension. So how can polyglot detect when it is needed?

If any lines like these appear (usually near the top of the file), that is a good indication that styled-components are being used.
```js
import styled from 'styled-components'
... require("styled-components") ...
... require('styled-components/native') ...
```
(Of course those could use `"` instead of `'`, may or may not be followed by a semicolon, and might even have additional whitespace.)

Realistically this search would only need to be done on Javascript or [compile-to-Javascript](https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js) files, such as JSX, TypeScript, CoffeeScript.

Another way to detect the presence of styled-components would be to look for a folder `"$(npm root)/styled-components"` but that doesn't seems very efficient.

**Comment by sheerun** [comment]
Sorry, it won't happen as it slows down loading of JS files

**Comment by alxndrsn** [comment]
I've adapted https://github.com/statico/vim-javascript-sql to create a plugin for highlighting JS tagged template literals starting with `css`.  It's available at https://github.com/alxndrsn/vim-javascript-css.

![Screenshot_2024-09-24_10-53-07](https://github.com/user-attachments/assets/e2851ea3-4558-4c82-b7c4-0db89633b16c)
