### ISSUE TITLE
"Official" Vim plugin in the swift repository

### ISSUE THREAD

**Issue by F4IL3D** [sheerun/vim-polyglot#381]
I recently discovered a vim plugin in the official swift repository.  It also seems to be regularly maintained as far as I have seen.

Here the link: https://github.com/apple/swift/tree/master/utils/vim

I use it at the moment and it seems to work better with my settings and theme (OneDark) than the plugin by Keith. But this can be quite a problem on my side.

Thanks for this great plugin

**Comment by sheerun** [comment]
I wish I could include it from official repository, but it is too big for build process of vim-polyglot to be efficient (over 50000 commits). Someone would need to extract it to separate repository or apple itself would need to do it

**Comment by F4IL3D** [comment]
Hello Adam,
Thank you for your answer. I can understand that. When I tested the plugin, I also had to clone the entire repository to use it. I have googled 2 days to find a way to download only a certain folder but unfortunately I did not find anything.
At the moment I am using this plugin https://github.com/bumaociyuan/vim-swift on my test machine. This guy did the work and extracted the plugin. Maybe that's an alternative for you. 

However, how long he will do this work and maintain the repository will be difficult to say.

**Comment by BMDan** [comment]
@sheerun wrote:
> but it is too big for build process of vim-polyglot to be efficient (over 50000 commits).

I'm confused by this comment.  The build script [downloads the tarball](https://github.com/sheerun/vim-polyglot/blob/9fd5c11a20f88525088c8635a3bc6a25ec4c05c7/build#L29) instead of `clone`ing; the number of commits therefore doesn't matter.  Outside of the build process, `--depth 1` (a "shallow clone") makes the number of commits irrelevant, while still preserving the ability to submit patches upstream.

**Comment by sheerun** [comment]
You're right, the bottleneck is number of files, not number of commits.
