### ISSUE TITLE
New JSX and TSX provider not working with coc.nvim

### ISSUE THREAD

**Issue by sQVe** [sheerun/vim-polyglot#409]
Hey :wave:,

The recent choice of using `vim-jsx-pretty` has created issues when using `coc.nvim` and `coc-tsserver` due to it always setting `javascript` and `typescript` as a filetype (dropping the `.jsx` and `.tsx`). 

I've also created an issue at `coc-tsserver` here: https://github.com/neoclide/coc-tsserver/issues/36

**Comment by sheerun** [comment]
This change was because `vim-jsx-pretty` support of JSX is far better than any alternatives, so reverting to old plugins is rather not an option.

As for `vim-jsx-pretty` setting `javascript` and `typescript` extensions I think it's reasonable:

JavaScript files that have JSX inside them often have `.js` extension, so to prevent parsing JS files and detecting JSX syntax inside them, all JS files had `javascript.jsx` filetype automatically set. Because JavaScript+JSX is superset of JavaScript (i.e. all JavaScript code is correct JavaScript+JSX) I think it's more reasonable to set their filetype just to `javascript` and let any "extension syntax" of javascript handle this filetype correctly instead introducing something like `javascript.jsx`.

I think most reasonable solution for `coc-tsserver` is be to JSX for all javascript files, i.e. treat `javascript` filetype the way like it would be `javascript.jsx` (again, `javascript` is always correct `javascript.jsx`).

Alternatively their plugin could automatically set filetype of all javascript files to `javascript.jsx` (like vim-polyglot did before today), but I would not recommend it.

**Comment by sQVe** [comment]
@sheerun I understand and agree with everything you're saying. I mainly wanted to note that there currently is a major issue between these two big plugins.

**Comment by sheerun** [comment]
In what way `coc.nvim` doesn't support `javascript` filetype with JSX? I tried it and it looks fine:

https://asciinema.org/a/GjEsfDDyszaub2jfkPyUcuU1U

**Comment by sQVe** [comment]
Ah. It seems to only be an issue with tsx / typescript. Sorry about that. I assumed that this was the case for jsx too.

**Comment by sheerun** [comment]
I guess I can make `typescript.jsx` extension for typescript a default as it's `tsx` is requirement for supporting JSX in typescript according to official docs: https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by sheerun** [comment]
Please see if it works now (v3.9.1)

**Comment by sQVe** [comment]
@sheerun I wonder if it is supposed to be typescript.jsx or typescript.jsx. vim-jsx uses typescript.jsx if I remember correctly.

I'll have to check this tomorrow.

**Comment by sQVe** [comment]
@sheerun Seems to work as expected now! :+1:
