### ISSUE TITLE
Issue with typescript indentation

### ISSUE THREAD

**Issue by sheerun** [sheerun/vim-polyglot#432]
Currently typescript has indentation issues because of vim-jsx-pretty. I'm aware of issue.

**Comment by sheerun** [comment]
@dkns I think it was because of styled-components. Can you check now?

**Comment by dkns** [comment]
Working perfectly now :+1: Thank you for all your hard work!

**Comment by Ironimus** [comment]
The problem in vim-styled-components seems to be fixed with [this commit](https://github.com/styled-components/vim-styled-components/commit/e499da283e187637a47eb0785d9f927e30b5194e).

Does it mean we can include styled-components into vim-polyglot again? I use it every day and it'd be great not to have to install it manually.

**Comment by insidewhy** [comment]
tsx files aren't indenting for me at all using latest versions of vim-jsx-pretty and yats.

**Comment by insidewhy** [comment]
If I add vim-styled-components to plug before vim-jsx-pretty, then indentation works :D
