### ISSUE TITLE
Typescript 3.7 optional chaining breaks on question mark

### ISSUE THREAD

**Issue by vcfvct** [sheerun/vim-polyglot#446]
**Does this bug happen when you install plugin without vim-polyglot?**
yes

**Describe the bug:**
The new optional chaining feature introduced in 3.7 breaks the syntax highlight.

**To Reproduce:**
Add question mark like `if(a.b?.c){...}`, all the code after this will not be correctly highlighted.

**Comment by nikersify** [comment]
`yats.vim`'s upstream supports this already https://github.com/HerringtonDarkholme/yats.vim/issues/141#issuecomment-554227149

**Comment by sheerun** [comment]
vim-polyglot should support it as well now

**Comment by jpribyl** [comment]
I ran `PlugUpdate` and it still seems to have this isssue. So, I deleted my install and re-installed.. I am still seeing the issue. 

If I disable `polyglot` and just use `yats.vim` then everything works. Is there some setting that must be updated in order to get support through `polyglot` ? Or maybe I must pull a different branch of this repo?
