### ISSUE TITLE
Angular files now incorrectly detected as 'jinja.html'

### ISSUE THREAD

**Issue by joerideg** [sheerun/vim-polyglot#560]
**Describe the bug:**
After [this commit](https://github.com/sheerun/vim-polyglot/commit/7e2d060f880a2d1d8e4742e27709869425983335) html detection is 'broken' for my Angular templates, it sets the filetype 'jinja.html' which breaks several of my plugins such as `coc-html` 

**To Reproduce:**
Update to that commit, 
Open an html file that has a `{{ }}` interpolation pattern in it.
result: `set ft?` is now jinja.html instead of html

**Comment by joerideg** [comment]
As of [your commit 3 minutes ago](https://github.com/sheerun/vim-polyglot/commit/e2bbed8acc1f1cf498a0085cf771cf9bf40fb709), it now detects it as djangohtml :)

**Comment by sheerun** [comment]
htmldjango should now be detected even after saving fresh .html file (if jinja tags are present in source)

**Comment by joerideg** [comment]
Hi @sheerun ,
I'm sorry if I was not clear. Before adding support for that jinja/djangohtml filetype detection my angular templates were detected as filetype 'html'. Now they are deteced as 'djangohtml', which is incorrect. Just because a template has `{{ }}` patterns in them does not mean they are django templates.

I would think at the very least polyglot should add 'html' to the filetype of any file that ends in .html so plugins that depend on 'html' filetype do not break.

**Comment by sheerun** [comment]
If anything it probably should be `html.django` becuase html is "outer" syntax and then jinja is inside it. Unfortunately it won't work if you try it and it seems there are often issues when combining different syntaxes this way. As far as I understand vim uses htmldjango instead of `html.django`, to have additional [htmldjango.vim](https://github.com/vim/vim/blob/master/runtime/syntax/htmldjango.vim) which not only loads django and html but also "glues" them together in proper way. I guess we need to establish what is the real goal here.

I guess there are two goals here with separate fixes:

1. Make sure Angular files are not recognized as htmldjango, but html or something like htmlangular
2. Make sure the same runtime files are loaded for htmldjango and html

I have question to you about 2. What files (or plugins) you are expecting vim to load for htmldjango filetype? i.e. what is not loaded for you now and would be loaded if filetype was named `html.django`? I know what theoretically, but I'm asking you for real things you are missing now

**Comment by sheerun** [comment]
as of 1. the angular templates should not longer be recognized as htmldjango, because i've removed {{ }} from heuristics

**Comment by sheerun** [comment]
also, would it be ok if angular files were marked html.mustache? without it there is no highlighting for code inside {{ }}

**Comment by joerideg** [comment]
Hi @sheerun thanks for your attention on this!

So I personally do not use django at all. So I have no information on that plugin. Personally I also do not care for highlighting in the brackets. So for me html filetype would be fine, so your latest commits fixes my personal issue, thanks for that! 

That being said I have checked and `coc-html` specifically supports the following filetypes out of the box:
`html`
`djangohtml`
`handlebars`

So if any of those help you highlight things I'm good with that :+1: (handlebars seem to have the nicest highlighting imho)

**Comment by sheerun** [comment]
I read coc-html actually uses htmldjango, not djangohtml. I'll make it detect html.mustache for now then
