### ISSUE TITLE
Polyglot stops vimtex to load.

### ISSUE THREAD

**Issue by TornaxO7** [sheerun/vim-polyglot#580]
`vimtex` isn't loaded anymore (I can't use any commands from vimtex).

**Does this bug happen when you install plugin without vim-polyglot?**
Yes.

**Describe the bug:**
If I'm commenting out `Plug 'sheerun/vim-polyglot'` than I can use the vimtex commands.

**To Reproduce:**
I'm using neovim (from the Arch repos)
in your `vimrc´:
```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
Open any `.tex` file and try `:VimtexInfo` it should work.
Now change your `vimrc`:
```vim
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
Plug 'lervag/vimtex'
call plug#end()
```
and open any `.tex` file and try `:VimtexInfo`. It shouldn't be available.

**Comment by sheerun** [comment]
It's because vim-plug adds files to runtimepath in the order they are defined. So if you `:echo &rtp`, then you get something like `/Users/sheerun/.vim,/Users/sheerun/.vim/plugged/vim-polyglot,/Users/sheerun/.vim/plugged/vim
tex,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim82,/usr/local/share/vim/vimfiles/a
fter,/Users/sheerun/.vim/plugged/vim-polyglot/after,/Users/sheerun/.vim/plugged/vimtex/after
,/Users/sheerun/.vim/after`

It's good for proper order of loading files when running something like `runtime! ftdetect/*.vim`, but unfortunately it also causes `autoload` commands to be loaded from first entry, which is vim-polyglot in this case. A workaround is to change order of plugins to:

```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'sheerun/vim-polyglot'
call plug#end()
```

Full fix probably involves vim-polyglot changing order of runtimepath or something..

**Comment by sheerun** [comment]
This issue is somewhat similar to https://github.com/lervag/vimtex/issues/1413 Probably the best solution is for vimtex to switch from tex filetype to vimtex filetype

**Comment by TornaxO7** [comment]
Changing the order of the plugins helped! Thank you and sorry for the late answer.

**Comment by sheerun** [comment]
I think this needs other solution than changing the order, I'll leave it open for now

**Comment by sheerun** [comment]
This should be now fixed, the order doesn't matter as vim-polyglot tries to use other vim files if they exist

**Comment by TornaxO7** [comment]
I can confirm it! It's working now even if this is in my `ini.vim` file:
```vim
Plug 'sheerun/vim-polyglot'
Plug 'lervag/vimtex'
```
Thank you very much!

**Comment by Freed-Wu** [comment]
I use <https://github.com/Shougo/dein.vim> as my vim package manager and met
the same problem. i check the repositories and notice in
<https://github.com/sheerun/vim-polyglot> and
<https://github.com/lervag/vimtex>, there are the `syntax/tex.vim` and
`ftplugin/tex.vim` in the same path with same file name. when `Dein
recache-runtimepath`, dein will copy files to a path such as
`~/.vim/.cache/init.vim/.dein`. so only one `syntax/tex.vim` and
`ftplugin/tex.vim` can exist -- they are `sheerun/vim-polyglot`'s.

excuse me, can the two files are moven to `after/` in order to avoid the
conflict?

i have tested it can work but i don't determine does there exist any other
problem.
