### ISSUE TITLE
Cannot set `g:polyglot_disabled` at the bottom of .vimrc

### ISSUE THREAD

**Issue by HaleTom** [sheerun/vim-polyglot#774]
**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

I have:

```
  call dein#add('tpope/vim-sleuth') " https://github.com/tpope/vim-sleuth
  call dein#add('sheerun/vim-polyglot')  " https://github.com/sheerun/vim-polyglot
```

When I execute: `:verbose Sleuth` I get no output.

Without loading polyglot, I get the expected output:
```
:setlocal expandtab     " from %                                                                                                                                                                                   
:setlocal shiftwidth=2  " from %
```

Work-around:

After `dein#add('sheerun/vim-polyglot')` but before `call dein#end()`:

```let g:polyglot_disabled = ['autoindent']```

This is not ideal as I prefer to have *configuration* of plugins in my `.vimrc`, and *loading* of plugins in a separate file.  I want to be able to have `g:polyglot_disabled` in my `.vimrc` after loading plugins (ie, after the `call dein#end()`).

**Comment by sheerun** [comment]
`g:polyglot_disabled` needs to be at the top

**Comment by HaleTom** [comment]
We agree on the work-around :)

Perhaps the configuration could be done upon `VimEnter` to allow this variable to be set anywhere?

**Comment by sheerun** [comment]
I wish, but:

1. vim-polyglot needs to be loaded before any external plugins it bundles, as it must override any plugin user might be already using in his/her .vimrc (e.g. vim-polyglot bundles `jparise/vim-graphql` which **must** to be loaded after also-bundled `MaxMEllon/vim-jsx-pretty`, which in turn  **must** be loaded after also-bundled `pangloss/vim-javascript`, plus **also** newest versions of them must be present). An unacceptable situation is when some plugin of mentioned plugins is installed in old version, or if it is an entirely different implementation, e.g. `Plug 'HerringtonDarkholme/yats.vim'` in user's .vimrc is not acceptable, as it is **not** compatible with `pangloss/vim-javascript` which directly-or-indirectly a dependency of both `MaxMEllon/vim-jsx-pretty` and `jparise/vim-graphql`)
2. vim-polyglot needs to support all current managers (e.g. vim 8 native packages or minpac which uses vim 8 native packages underneath) and vim-native plugin manager (e.g. vim-plug, pathogen, neobundle etc.)

Because of the requirements above and the facts that:
1. the the loading of external plugins can be blocked only by loading any vim-polyglot code
2. any commands, including `VimEnter` can be overridden by plugins

the configuration variables cannot be set on `VimEnter`, as by then external plugins are already loaded by vim-native behavior (e.g. vim 8 native packages, or minpac which uses vim 8 native packages underneath, or plugin manager used by user, like pathogen, neobundle, vim-plug etc.)

Going back to `g:polyglot_disabled`, Vim Polyglot checks this variable to tell whether it should override or not some external plugin that user already has in his/her .vimrc (or in `.vim/pack` or `.vim/start` along Vim Polyglot, if one uses vim 8 native packagers). It happens more often than you think e.g. many users have 'HerringtonDarkholme/yats.vim' in their vimrc which must be prevented from loading by vim-polyglot, as it bundles `pangloss/vim-javascript` and its dependencies). Because of this `g:polyglot_disabled` cannot be loaded in any after-command like `VimEnter`, as these can be set or overridden by any plugin. It certainly doesn't help that vim 8 packages are loaded alphabetically and not in the order defined in .vimrc.

If you somehow manage to comprehend the above ;) you'll understand that.... it's complicated matter.  I have good reason to require `g:polyglot_disabled` to be set before vim-polyglot is loaded, as only then I have full control what is loaded or not before vim-polyglot, which is needed for proper working or dependencies, and `g:polyglot_disabled` feature in itself.

**Comment by HaleTom** [comment]
Thanks for the detailed explanation and all your work on this plugin!
