### ISSUE TITLE
Neovim/Vim8 support broken because of `vim9script` in `autoload/polyglot/ft.vim`

### ISSUE THREAD

**Issue by lithammer** [sheerun/vim-polyglot#779]
**Does this bug happen when you install plugin without vim-polyglot?**

No.

**Describe the bug:**

Changes to `autoload/polyglot/ft.vim` in b77c5f11070ecb2ff343aa18b4ea859e6168f16c seems to introduce a bunch of Vim 9 stuff not supported by Neovim (and never will be?). It also breaks on older versions of Vim.

**To Reproduce:**

Open a shell script, e.g. `nvim foo.sh`.

**Comment by giorgi-kiknavelidze** [comment]
can confirm. opening a .env file with neovim also results in similar errors.

**Comment by c60cb859** [comment]
These types also causes this problem
```
nvim foo.xml
nvim foo.bash
nvim foo.tex
```

**Comment by EmilKronborg** [comment]
Perl scripts also cause this issue

```sh
$ nvim foo.pl
```

**Comment by kmoschcau** [comment]
This not only breaks neovim, but also vim<9, if you try to source the file. I haven't yet checked if the same thing happens when the file is sourced as part of file detect. Might be that vim has some recovery there.

**Comment by Frederick888** [comment]
There actually been vim9scripts in vim-polyglot for some time since ff8c1d76741f148d5f6efb9a57119dcf11afaec6 (see [1]).

Since AFAIK Vim9 is not officially out yet, perhaps we can block vim9script updates for now?

In the future we can introduce some sort of mechanism that makes a new copy of a plugin if it starts using vim9script, and load one of them according to has(...) checks. Or maybe simply have 2 release branches for Vim and NeoVim?

[1] https://github.com/bohlender/vim-smt2

**Comment by halostatue** [comment]
PR #780 will fix this for Vim8. The `vim9script` command exists to allow the implementation and testing of vim 9 script for current releases of vim.

**Comment by jsatk** [comment]
I'm confused as to why this issue is closed. It's still an issue and affects neovim as well as vim8.

**Comment by xfzv** [comment]
> I'm confused as to why this issue is closed. It's still an issue and affects neovim as well as vim8.

Huh? it's not closed, #781 (which is a duplicate) is.

![image](https://user-images.githubusercontent.com/78810647/154756230-cf74ab6b-faef-4ed1-a10d-dc4263494ed5.png)

**Comment by n-kev1n** [comment]
> opening an HTML file in Neovim also causes errors. Looks like I'm going back to vim first.

same thing has been happening to me too, when I try to edit .html files

**Comment by kmoschcau** [comment]
Just FYI, it shouldn't matter which file type you open. This bug is in the file type detection code. So unless the file you open is already detected by something else, you are going to run into this. For example opening a file that is supported by tree-sitter will not have this problem.

**Comment by sheerun** [comment]
weird, I don't have this issue on my machine... I'll try to reproduce

**Comment by sheerun** [comment]
could anyone post their exact nvim / vim version and maybe .vimrc?

**Comment by n-kev1n** [comment]
for me, It happened when I updated my neovim version.
I'm currently using neovim-nightly

`current version: 0.7.0`

I'll try to test on my other machine that has nvim 6.0

**Comment by Frederick888** [comment]
I'm using NeoVim 0.6.1 and my full vimrc is at https://git.tsundere.moe/Frederick888/frederick-settings/-/blob/master/.vimrc

I bumped this issue when editing a PKGBUILD file under Arch.

**Comment by juanlufont** [comment]
I can reproduce with vim 8.2 in Debian Stable (Bullseye):
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
```

This is a basic .vimrc that allows me to reproduce the error:
```
set nocompatible
syntax on
filetype plugin on

set encoding=UTF-8
set expandtab
set linebreak
set number
set shiftwidth=4
set tabstop=4

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
  Plug 'junegunn/vim-plug'
  let g:polyglot_disabled = ['markdown']
  Plug 'sheerun/vim-polyglot'
call plug#end()
```

The above configuration throws these error messages:
```
Error detected while processing BufNewFile Autocommands for "*.sh":
E117: Unknown function: polyglot#ft#SetFileTypeSH
E117: Unknown function: polyglot#ft#SetFileTypeSH
```

**Comment by halostatue** [comment]
@sheerun I’m on MacVim 8.2

```
VIM Vi IMproved 8.2 (2019 Dec 12, compiled Sep 24 2021 14:13:29)
macOS version arm64
Included patches• 1-3455
```

My `.vimrc` is fairly complex, but the fix I put in at #780 works for me and should not break for possible later versions.

**Comment by kavinvalli** [comment]
I'm getting the same issue on html files, .env files etc
<img width="1552" alt="Screenshot 2022-02-20 at 8 48 37 AM" src="https://user-images.githubusercontent.com/41034356/154827021-2182b5ac-c03c-42b5-b00f-a56d0294cae0.png">

**Comment by giack-dev** [comment]
I also am having this issue using Neovim

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

i am facing the issue when opening files that have the following extensions:
- foo.c
- foo.sh
- foo.xml
- foo.html

This is the error output i get:
![polyglot issue](https://user-images.githubusercontent.com/84200346/154841128-590a77b6-0b76-45ee-b7ad-fddc4c34f7b8.png)

**Comment by luisdavim** [comment]
No issues with:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 16 2022 17:51:47)
macOS version - x86_64
Included patches: 1-4400
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-version-min=12.0 -fstack-protector-strong -L/usr/local/lib -L/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE -lperl -L/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin -lpython3.10 -framework CoreFoundation -lruby.3.1 -L/usr/local/Cellar/ruby/3.1.0/lib
```

but breaks with:

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

I'm using the same config for both that can be found in https://github.com/luisdavim/dotfiles/tree/master/files/vim I think the issue is that `nvim` doesn't support `vim9script`

**Comment by bilalq** [comment]
I started getting errors when opening shell script files. As a short-term workaround, you can pin polyglot to an older version. This is what I'm using with Plug:

```vim
Plug 'sheerun/vim-polyglot', { 'commit': '2c5af8f' }
```

**Comment by halostatue** [comment]
This is going to be an ongoing problem, because neovim isn’t going to support vim9script and Vim isn’t going to have the deep Lua integration that neovim has.

People who choose to build treesitter-based syntax highlighters (which is the way that the neovim community seems to be pushing) aren’t going to be building non-treesitter-based syntax highlighters for compatibility with Vim 8 and Vim 9. At this point, I believe we are seeing the start of a non-negotiable break between the two variations.

I think that the fix that I have in #780 is the correct choice for Vim support, unless the choice is made to keep polyglot wholly pure-vim-script compatible and avoid vim9script (which would be achieved by reverting the change introducing it). At that point, there’s a question as to what happens when a language decides to support either treesitter-based or vim9script-based syntax highlighting instead of the lowest common denominator between the two trees.

Because I have yet to find a viable neovim-based alternative to MacVim, I am _highly_ unlikely to shift into the neovim ecosystem, and may start looking at using vim9script for my own scripts and plugins.

**Comment by halostatue** [comment]
So somewhere between path 3995 and 4400 is a fix where `export` in an autoload file causes the export to include the necessary.

> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 16 2022 17:51:47)
> macOS version - x86_64
> Included patches: 1-4400

For my purposes, this would be useful if a MacVim release were made as suggested in macvim-dev/macvim#1235.

**Comment by dmitmel** [comment]
Vim9script doesn't bring anything new with regards to syntax highlighting in Vim, Vim9script syntax files would still be just a bunch of `:syntax` statements, which is why it doesn't make much sense to use it for this purpose, so I believe that regular Vimscript remains the lowest common denominator, as it used to be. However, the file responsible for the problem in this ticket is originally [part of the Vim runtime](https://github.com/vim/vim/blob/master/runtime/autoload/dist/ft.vim), it contains internal functions of filetype detection, and I am fairly certain that it was rewritten in Vim9script for improving performance (most logic in the functions is iterating the file line-by-line and checking the strings for various patterns - I can see how Vim9script would be beneficial in this case). It also doesn't use any fundamentally new features of Vim9script, mostly just old keywords swapped for new ones ([diff](https://github.com/vim/vim/commit/a2baa73d1d33014adea0fd9567949089ca21a782#diff-eacc3172370ae087a8cfbfee30922eccb8a166e55ea33062b557d03a126bda8c)), so I think that reverting the update to it and backporting future changes to that script is the way to go for now.

**Comment by halostatue** [comment]
You’re right that vim9script doesn’t add anything to syntax highlighting, but eventually people will choose to write their plugins in `vim9script` instead of `vimscript` just as hardcore neovim people are starting to write their plugins in nvim-Lua. I believe that this has been an inevitable collision between neovim and vim since both are pushing hard in their respective directions, and plug-in authors will eventually be left with unenviable choices: keep the slowest LCD, or implement parts or all of their plug-ins twice.

**Comment by sheerun** [comment]
So, I've reproduced this issue, and changed vim repository commit to fetch changes from (the one that haven't migrated to vim9script yet). Thank you for patience!
